nodes:
  www:
    ami: ami-25a3764c
    instance-type: "m1.small"
    username: ubuntu

    ## following only necessary for deployment
    availability-zone: "us-east-1a" # customers *could* specify this, probably shouldn't care.
    public-key: "www.id_rsa.pub"
    private-key: "www.id_rsa"
    security-groups: ["www"]

jobs:
  build:
    template: build
    node: www   # name of node to use. unique per-project
    commands:
      - rvm use jruby-1.6.5@circle --default
      - bundle install
      - lein deps
      - bundle exec rspec spec
      - lein midje:
          environment:
            CIRCLE_ENV: "staging"
    #  on-success: deploy # another build to trigger if this one is successful
    notify_emails:
      # Recognized keys, :committer, :owner, or email literals.
      - :committer
      - :owner

  deploy:
    template: deploy
    node: www
    notify_emails:
      - :owner

    commands:
      - rvm use jruby-1.6.5@circle --default
      - bundle install
      - lein deps
      - rake production:server:
          environment:
            CIRCLE_SWANK: "true"
      - sudo /etc/init.d/nginx start

  staging:
    template: staging
    node: www
    notify_emails:
      - :owner

    commands:
      - rvm use jruby-1.6.5@circle --default
      - bundle install
      - lein deps
      - rake staging:server
      - sudo /etc/init.d/nginx start

schedule:
  commit:
    job: build
  nightly:
    job: long-tests

    # branches:
    #   only:
    #   exclude: