development:
  host: localhost
  database: circle

test:
  host: localhost
  database: mongoid_test_test

# TODO: add staging here, and DRY with the backend.

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOHQ_HOST'] %>
  port: <%= ENV['MONGOHQ_PORT'] %>
  username: <%= ENV['MONGOHQ_PASSWORD'] %>
  password: <%= ENV['MONGOHQ_PASSWORD'] %>
  database: <%= ENV['MONGOHQ_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

staging:
  host: staff.mongohq.com
  port: 10017
  username: circle
  password: "construction-ship-plates-proud"
  database: staging
