spidermonkey:
  type: autotools
  repo: http://hg.mozilla.org/mozilla-central

  autoconf:
    version: 2.13

  subdir: js/src

  configurations:
    - --enable-optimize --disable-debug
    - --disable-optimize --enable-debug


